//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkTechHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestMaster
    {
        public int RequestId { get; set; }
        public Nullable<int> RequestedFor { get; set; }
        public string RequestMsg { get; set; }
        public string RequestedBy { get; set; }
        public Nullable<System.DateTime> RequestDt { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual DeveloperMaster DeveloperMaster { get; set; }
        public virtual ProjectMaster ProjectMaster { get; set; }
    }
}
