//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkTechHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadCodeMaster
    {
        public int UploadId { get; set; }
        public string Title { get; set; }
        public string Descripition { get; set; }
        public string UploadedBy { get; set; }
        public string CodeFileName { get; set; }
        public Nullable<System.DateTime> UploadedOn { get; set; }
    
        public virtual DeveloperMaster DeveloperMaster { get; set; }
    }
}
