//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkTechHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkReportMaster
    {
        public int ReportId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> WorkDate { get; set; }
        public Nullable<bool> IsHelpNeeded { get; set; }
        public string SubmittedBy { get; set; }
        public Nullable<System.DateTime> SubmittedOn { get; set; }
    
        public virtual DeveloperMaster DeveloperMaster { get; set; }
    }
}
